### PR TITLE
Store wfuzz configuration according to XDG Base Directory Specification

### LINKED ISSUE #129: wfuzz shouldn't store its configuration in the user home directory
According to the XDG Base Directory Specification user-specific configuration files should be stored at `$XDG_CONFIG_HOME` or `$HOME/.config`. 
See: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

https://github.com/xmendez/wfuzz/blob/bc67d05b435808de36315e385ef0e09422b2ebb0/src/wfuzz/facade.py#L15-L16

This line should be changed to something like:
```python
     def get_config_file(self): 
         return os.path.join(utils.get_config_dir(), "wfuzz.ini") 
```
If you're up to that I'd like to work on it just assign it to me.

### PR DESCRIPTION
**Pull request by nemoload**
Fixes #129

### CODE REVIEW

**Comment by xmendez** [comment]
@nemoload I totally missed this PR when working on release 3.0.0. 
Can you please resolve the conflicts with the newer version?

thanks

**Comment by nemoload** [comment]
No problem.

**Comment by nemoload** [comment]
@xmendez Done

**Comment by xmendez** [comment]
Thanks

**Pull request merged**
